[2025-01-29T11:13:12.898+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T11:13:12.927+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.customer_Load_redshift manual__2025-01-29T11:12:34.645629+00:00 [queued]>
[2025-01-29T11:13:12.941+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.customer_Load_redshift manual__2025-01-29T11:12:34.645629+00:00 [queued]>
[2025-01-29T11:13:12.941+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T11:13:12.962+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): customer_Load_redshift> on 2025-01-29 11:12:34.645629+00:00
[2025-01-29T11:13:12.974+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1803) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T11:13:12.980+0000] {standard_task_runner.py:72} INFO - Started process 1805 to run task
[2025-01-29T11:13:12.977+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'customer_Load_redshift', 'manual__2025-01-29T11:12:34.645629+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpklvfndl4']
[2025-01-29T11:13:12.982+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask customer_Load_redshift
[2025-01-29T11:13:13.088+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.customer_Load_redshift manual__2025-01-29T11:12:34.645629+00:00 [running]> on host ae52aba2dca2
[2025-01-29T11:13:13.312+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='customer_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T11:12:34.645629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T11:12:34.645629+00:00'
[2025-01-29T11:13:13.317+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T11:13:14.761+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T11:13:14.762+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T11:13:14.779+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T11:13:14.781+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=customer_Load_redshift, run_id=manual__2025-01-29T11:12:34.645629+00:00, execution_date=20250129T111234, start_date=20250129T111312, end_date=20250129T111314
[2025-01-29T11:13:14.849+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T11:13:14.870+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T11:13:14.873+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
