[2025-01-29T12:20:23.780+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T12:20:23.804+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.location_Load_redshift manual__2025-01-29T12:17:16.105169+00:00 [queued]>
[2025-01-29T12:20:23.817+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.location_Load_redshift manual__2025-01-29T12:17:16.105169+00:00 [queued]>
[2025-01-29T12:20:23.817+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-01-29T12:20:23.836+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): location_Load_redshift> on 2025-01-29 12:17:16.105169+00:00
[2025-01-29T12:20:23.849+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'location_Load_redshift', 'manual__2025-01-29T12:17:16.105169+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmphl1ij71s']
[2025-01-29T12:20:23.852+0000] {standard_task_runner.py:105} INFO - Job 86: Subtask location_Load_redshift
[2025-01-29T12:20:23.847+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2873) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T12:20:23.853+0000] {standard_task_runner.py:72} INFO - Started process 2882 to run task
[2025-01-29T12:20:23.924+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.location_Load_redshift manual__2025-01-29T12:17:16.105169+00:00 [running]> on host ae52aba2dca2
[2025-01-29T12:20:24.028+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='location_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T12:17:16.105169+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T12:17:16.105169+00:00'
[2025-01-29T12:20:24.030+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T12:20:25.294+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T12:20:25.295+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T12:20:25.311+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T12:20:25.312+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=location_Load_redshift, run_id=manual__2025-01-29T12:17:16.105169+00:00, execution_date=20250129T121716, start_date=20250129T122023, end_date=20250129T122025
[2025-01-29T12:20:25.365+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T12:20:25.387+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T12:20:25.390+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
