[2025-01-29T11:13:01.165+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T11:13:01.316+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.location_Load_redshift manual__2025-01-29T11:12:34.645629+00:00 [queued]>
[2025-01-29T11:13:01.337+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.location_Load_redshift manual__2025-01-29T11:12:34.645629+00:00 [queued]>
[2025-01-29T11:13:01.338+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T11:13:01.407+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): location_Load_redshift> on 2025-01-29 11:12:34.645629+00:00
[2025-01-29T11:13:01.603+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1760) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T11:13:01.630+0000] {standard_task_runner.py:72} INFO - Started process 1784 to run task
[2025-01-29T11:13:01.674+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'location_Load_redshift', 'manual__2025-01-29T11:12:34.645629+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp6c8v614t']
[2025-01-29T11:13:01.702+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask location_Load_redshift
[2025-01-29T11:13:02.450+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.location_Load_redshift manual__2025-01-29T11:12:34.645629+00:00 [running]> on host ae52aba2dca2
[2025-01-29T11:13:03.917+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='location_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T11:12:34.645629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T11:12:34.645629+00:00'
[2025-01-29T11:13:03.925+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T11:13:07.742+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T11:13:07.746+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T11:13:07.773+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T11:13:07.775+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=location_Load_redshift, run_id=manual__2025-01-29T11:12:34.645629+00:00, execution_date=20250129T111234, start_date=20250129T111301, end_date=20250129T111307
[2025-01-29T11:13:07.845+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T11:13:07.911+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T11:13:07.924+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
