[2025-01-29T11:41:34.073+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T11:41:34.151+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.location_Load_redshift manual__2025-01-29T11:41:02.227708+00:00 [queued]>
[2025-01-29T11:41:34.183+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.location_Load_redshift manual__2025-01-29T11:41:02.227708+00:00 [queued]>
[2025-01-29T11:41:34.184+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T11:41:34.231+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): location_Load_redshift> on 2025-01-29 11:41:02.227708+00:00
[2025-01-29T11:41:34.333+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T11:41:34.363+0000] {standard_task_runner.py:72} INFO - Started process 2196 to run task
[2025-01-29T11:41:34.382+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'location_Load_redshift', 'manual__2025-01-29T11:41:02.227708+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpu5vve615']
[2025-01-29T11:41:34.406+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask location_Load_redshift
[2025-01-29T11:41:34.741+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.location_Load_redshift manual__2025-01-29T11:41:02.227708+00:00 [running]> on host ae52aba2dca2
[2025-01-29T11:41:35.287+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='location_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T11:41:02.227708+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T11:41:02.227708+00:00'
[2025-01-29T11:41:35.350+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T11:41:44.785+0000] {job.py:229} INFO - Heartbeat recovered after 11.02 seconds
[2025-01-29T11:41:46.786+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T11:41:46.804+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T11:41:46.858+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T11:41:46.862+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=location_Load_redshift, run_id=manual__2025-01-29T11:41:02.227708+00:00, execution_date=20250129T114102, start_date=20250129T114134, end_date=20250129T114146
[2025-01-29T11:41:46.971+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T11:41:47.043+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T11:41:47.048+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
