[2025-01-29T11:41:33.924+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T11:41:34.039+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.product_Load_redshift manual__2025-01-29T11:41:02.227708+00:00 [queued]>
[2025-01-29T11:41:34.072+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.product_Load_redshift manual__2025-01-29T11:41:02.227708+00:00 [queued]>
[2025-01-29T11:41:34.073+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T11:41:34.125+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): product_Load_redshift> on 2025-01-29 11:41:02.227708+00:00
[2025-01-29T11:41:34.263+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T11:41:34.287+0000] {standard_task_runner.py:72} INFO - Started process 2190 to run task
[2025-01-29T11:41:34.288+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'product_Load_redshift', 'manual__2025-01-29T11:41:02.227708+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpoev7vds6']
[2025-01-29T11:41:34.319+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask product_Load_redshift
[2025-01-29T11:41:34.716+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.product_Load_redshift manual__2025-01-29T11:41:02.227708+00:00 [running]> on host ae52aba2dca2
[2025-01-29T11:41:35.283+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='product_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T11:41:02.227708+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T11:41:02.227708+00:00'
[2025-01-29T11:41:35.345+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T11:41:44.790+0000] {job.py:229} INFO - Heartbeat recovered after 11.13 seconds
[2025-01-29T11:41:47.039+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T11:41:47.050+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T11:41:47.112+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T11:41:47.115+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=product_Load_redshift, run_id=manual__2025-01-29T11:41:02.227708+00:00, execution_date=20250129T114102, start_date=20250129T114134, end_date=20250129T114147
[2025-01-29T11:41:47.253+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T11:41:47.342+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-01-29T11:41:47.358+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T11:41:47.364+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
